<?xml version="1.0" encoding="ASCII"?>
<xfw:XFWPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:xfw="http://ru.croc.ctp.jxfw/metamodel" name="jxfwmodel" nsURI="http://ru.croc.ctp.jxfw/XFWPackage/jxfwmodel" nsPrefix="jxfwmodel">
  <eSubpackages xsi:type="xfw:XFWPackage" name="ru.croc.ctp.audit.domain" nsURI="http://ru.croc.ctp.jxfw/XFWPackage/ru.croc.ctp.audit.domain" nsPrefix="ru.croc.ctp.audit.domain">
    <eClassifiers xsi:type="xfw:XFWDataSource" name="LocalityNames" instanceClassName="ru.croc.ctp.survey.datasource.LocalityNames" requestMapping="_plain/LocalityNames"/>
    <eClassifiers xsi:type="xfw:XFWClass" name="ActionLog" instanceClassName="ru.croc.ctp.audit.domain.ActionLog" keyTypeName="java.lang.String" persistenceType="FULL">
      <eAnnotations source="http://www.croc.ru/ctp/model/XFWObject">
        <details key="isReadonly" value="false"/>
        <details key="persistence" value="FULL"/>
      </eAnnotations>
      <eAnnotations source="http://www.croc.ru/ctp/model/Entity">
        <details key="name" value=""/>
      </eAnnotations>
      <eAnnotations source="http://www.croc.ru/ctp/model/XFWToString">
        <details key="includeFieldNames" value="true"/>
        <details key="of" value="[]"/>
        <details key="exclude" value="[]"/>
        <details key="callSuper" value="false"/>
        <details key="hashcode" value="false"/>
        <details key="identityHashcode" value="false"/>
      </eAnnotations>
      <eAnnotations source="http://www.croc.ru/ctp/model/SuppressWarnings">
        <details key="value" value="[all]"/>
      </eAnnotations>
      <eAnnotations source="http://www.croc.ru/ctp/model/i18n">
        <details key="value" value="&#x416;&#x443;&#x440;&#x43d;&#x430;&#x43b; &#x410;&#x443;&#x434;&#x438;&#x442;&#x430;"/>
        <details key="lang" value="ru"/>
        <details key="propName" value=""/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="xfw:XFWAttribute" name="applicationId" unsettable="true">
        <eAnnotations source="http://www.croc.ru/ctp/model/i18n">
          <details key="value" value="&#x418;&#x434;&#x435;&#x43d;&#x442;&#x438;&#x444;&#x438;&#x43a;&#x430;&#x442;&#x43e;&#x440; &#x43f;&#x440;&#x438;&#x43b;&#x43e;&#x436;&#x435;&#x43d;&#x438;&#x44f;"/>
          <details key="lang" value="ru"/>
          <details key="propName" value=""/>
        </eAnnotations>
        <eAnnotations source="http://www.croc.ru/ctp/model/column">
          <details key="length" value="255"/>
        </eAnnotations>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="xfw:XFWAttribute" name="objectType" unsettable="true">
        <eAnnotations source="http://www.croc.ru/ctp/model/i18n">
          <details key="value" value="&#x422;&#x438;&#x43f; &#x43e;&#x431;&#x44a;&#x435;&#x43a;&#x442;&#x430;"/>
          <details key="lang" value="ru"/>
          <details key="propName" value=""/>
        </eAnnotations>
        <eAnnotations source="http://www.croc.ru/ctp/model/column">
          <details key="length" value="255"/>
        </eAnnotations>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="xfw:XFWAttribute" name="objectId" unsettable="true">
        <eAnnotations source="http://www.croc.ru/ctp/model/i18n">
          <details key="value" value="&#x418;&#x434;&#x435;&#x43d;&#x442;&#x438;&#x444;&#x438;&#x43a;&#x430;&#x442;&#x43e;&#x440; &#x43e;&#x431;&#x44a;&#x435;&#x43a;&#x442;&#x430;"/>
          <details key="lang" value="ru"/>
          <details key="propName" value=""/>
        </eAnnotations>
        <eAnnotations source="http://www.croc.ru/ctp/model/column">
          <details key="length" value="255"/>
        </eAnnotations>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="xfw:XFWAttribute" name="objectState" unsettable="true">
        <eAnnotations source="http://www.croc.ru/ctp/model/i18n">
          <details key="value" value="C&#x43e;&#x441;&#x442;&#x43e;&#x44f;&#x43d;&#x438;&#x435; &#x43e;&#x431;&#x44a;&#x435;&#x43a;&#x442;&#x430;"/>
          <details key="lang" value="ru"/>
          <details key="propName" value=""/>
        </eAnnotations>
        <eAnnotations source="http://www.croc.ru/ctp/model/column">
          <details key="length" value="255"/>
        </eAnnotations>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="xfw:XFWAttribute" name="objectStateOld" unsettable="true">
        <eAnnotations source="http://www.croc.ru/ctp/model/i18n">
          <details key="value" value="&#x41f;&#x440;&#x435;&#x434;&#x44b;&#x434;&#x443;&#x449;&#x435;&#x435; &#x441;&#x43e;&#x441;&#x442;&#x43e;&#x44f;&#x43d;&#x438;&#x435; &#x43e;&#x431;&#x44a;&#x435;&#x43a;&#x442;&#x430;"/>
          <details key="lang" value="ru"/>
          <details key="propName" value=""/>
        </eAnnotations>
        <eAnnotations source="http://www.croc.ru/ctp/model/column">
          <details key="length" value="255"/>
        </eAnnotations>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="xfw:XFWReference" name="parentLog" eType="//ru.croc.ctp.audit.domain/ActionLog" unsettable="true">
        <eAnnotations source="http://www.croc.ru/ctp/model/i18n">
          <details key="value" value="&#x421;&#x441;&#x44b;&#x43b;&#x43a;&#x430; &#x43d;&#x430; &#x440;&#x43e;&#x434;&#x438;&#x442;&#x435;&#x43b;&#x44c;&#x441;&#x43a;&#x438;&#x439; &#x43b;&#x43e;&#x433;"/>
          <details key="lang" value="ru"/>
          <details key="propName" value=""/>
        </eAnnotations>
        <eAnnotations source="http://www.croc.ru/ctp/model/ManyToOne">
          <details key="targetEntity" value="void"/>
          <details key="cascade" value="[]"/>
          <details key="fetch" value="EAGER"/>
          <details key="optional" value="true"/>
        </eAnnotations>
        <eAnnotations source="http://www.croc.ru/ctp/model/relation_column">
          <details key="name" value="XFWManyToOne"/>
          <details key="lazyLoad" value="false"/>
          <details key="container" value="ActionLog"/>
          <details key="actualType" value="ru.croc.ctp.audit.domain.ActionLog"/>
        </eAnnotations>
        <eAnnotations source="http://www.croc.ru/ctp/model/column"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="xfw:XFWAttribute" name="userId" unsettable="true">
        <eAnnotations source="http://www.croc.ru/ctp/model/i18n">
          <details key="value" value="&#x41f;&#x43e;&#x43b;&#x44c;&#x437;&#x43e;&#x432;&#x430;&#x442;&#x435;&#x43b;&#x44c;"/>
          <details key="lang" value="ru"/>
          <details key="propName" value=""/>
        </eAnnotations>
        <eAnnotations source="http://www.croc.ru/ctp/model/column">
          <details key="length" value="255"/>
        </eAnnotations>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="xfw:XFWAttribute" name="actionTs" defaultValueLiteral="now" unsettable="true">
        <eAnnotations source="http://www.croc.ru/ctp/model/i18n">
          <details key="value" value="&#x414;&#x430;&#x442;&#x430; &#x438; &#x432;&#x440;&#x435;&#x43c;&#x44f; &#x434;&#x435;&#x439;&#x441;&#x442;&#x432;&#x438;&#x44f;"/>
          <details key="lang" value="ru"/>
          <details key="propName" value=""/>
        </eAnnotations>
        <eAnnotations source="http://www.croc.ru/ctp/model/XFWDefaultValue">
          <details key="value" value=""/>
          <details key="asCurrent" value="true"/>
        </eAnnotations>
        <eAnnotations source="http://www.croc.ru/ctp/model/column"/>
        <eType xsi:type="ecore:EDataType" href="http://ru.croc.ctp.jxfw/metamodel#//LocalDateTime"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="xfw:XFWAttribute" name="info" unsettable="true">
        <eAnnotations source="http://www.croc.ru/ctp/model/i18n">
          <details key="value" value="&#x41f;&#x440;&#x43e;&#x438;&#x437;&#x432;&#x43e;&#x43b;&#x44c;&#x43d;&#x430;&#x44f; &#x434;&#x43e;&#x43f;&#x43e;&#x43b;&#x43d;&#x438;&#x442;&#x435;&#x43b;&#x44c;&#x43d;&#x430;&#x44f; &#x438;&#x43d;&#x444;&#x43e;&#x440;&#x43c;&#x430;&#x446;&#x438;&#x44f;"/>
          <details key="lang" value="ru"/>
          <details key="propName" value=""/>
        </eAnnotations>
        <eAnnotations source="http://www.croc.ru/ctp/model/column">
          <details key="length" value="255"/>
        </eAnnotations>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="xfw:XFWAttribute" name="id" unsettable="true">
        <eAnnotations source="http://www.croc.ru/ctp/model/Id"/>
        <eAnnotations source="http://www.croc.ru/ctp/model/column">
          <details key="length" value="255"/>
        </eAnnotations>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="xfw:XFWAttribute" name="ts" unsettable="true">
        <eAnnotations source="http://www.croc.ru/ctp/model/Version"/>
        <eAnnotations source="http://www.croc.ru/ctp/model/column"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
      </eStructuralFeatures>
      <persistenceModule>JPA</persistenceModule>
    </eClassifiers>
  </eSubpackages>
</xfw:XFWPackage>
