//This file has been generated and should not be edited by hand
define({
	"model.Software": "Программное обеспечение",
	"model.Software.name": "Наименование",
	"model.Software.project": "Проект",
	"model.Software.specification": "Спецификация на разработку",
	"model.Software.isBought": "Покупное",
	"model.Software.manuals": "Документация ПО",
	"model.Task": "Задача",
	"model.Task.performers": "Исполнители",
	"model.Task.project": "Проект",
	"model.Task.description": "Описание",
	"model.Task.subject": "Тема",
	"model.City": "Город",
	"model.City.archive": "Архивное значение",
	"model.City.name": "Название",
	"model.City.description": "Описание",
	"model.City.code": "Код",
	"model.Employee": "Сотрудник",
	"model.Employee.birthDay": "Дата рождения",
	"model.Employee.resource": "Испольузуемые ресурсы",
	"model.Employee.tasks": "Задачи",
	"model.Employee.signPublicKey": "Открытый ключ подписи",
	"model.Employee.projects": "Участвует в проектах",
	"model.Employee.photo": "Фотография",
	"model.Employee.resume": "Резюме",
	"model.Employee.login": "Логин",
	"model.Employee.factor": "Коэффициент",
	"model.Employee.isManager": "Является менеджером",
	"model.Employee.phoneHome": "Домашний телефон",
	"model.Employee.info": "Комментарий",
	"model.Employee.skills": "Опыт работы",
	"model.Employee.qualification": "Квалификация",
	"model.Employee.employeeAddress": "Адрес",
	"model.Employee.salary": "Зарплата",
	"model.Employee.lastPass": "Регистрация на проходной",
	"model.Employee.passID": "Идентификатор эл. пропуска",
	"model.Employee.department": "Работает в отделе",
	"model.Subject": "Subject",
	"model.Subject.middleName": "Отчество",
	"model.Subject.firstName": "Имя",
	"model.Subject.lastName": "Фамилия",
	"model.GetObjectRequest": "GetObjectRequest",
	"model.GetObjectRequest.typeName": "typeName",
	"model.GetObjectRequest.objectID": "objectID",
	"model.EmployeeFilterByLastName": "EmployeeFilterByLastName",
	"model.EmployeeFilterByLastName.lastName": "lastName",
	"model.Address": "Address",
	"model.Address.city": "Город",
	"model.Address.flat": "Квартира",
	"model.Address.street": "Улица",
	"model.Address.house": "Дом",
	"model.Project": "Проект",
	"model.Project.navisionID": "Идентификатор Navision",
	"model.Project.department": "Выполняется отделом",
	"model.Project.tasks": "Задачи проекта",
	"model.Project.name": "Наименование",
	"model.Project.crew": "Участники проекта",
	"model.ByDepFlt": "Фильтр Департамента",
	"model.ByDepFlt.byParent": "Вышестоящий департамент",
	"model.ByDepFlt.byName": "Наименование",
	"model.Qualification": "Qualification",
	"model.Qualification.Empty": "Пусто",
	"model.Qualification.Secretary": "Секретарь",
	"model.Qualification.Administrator": "Администратор",
	"model.Qualification.Documentator": "Документатор",
	"model.Qualification.TestEngineer": "Тест Инженер",
	"model.Qualification.Engineer": "Инженер",
	"model.Qualification.Developer": "Разработчик",
	"model.Qualification.Designer": "Дизайнер",
	"model.Qualification.Analyst": "Аналитик",
	"model.Qualification.TeamManager": "Менеджер",
	"model.Qualification.DepartmentManager": "Начальник отдела",
	"model.DocImage": "Образ документа",
	"model.DocImage.authors": "Авторы",
	"model.DocImage.document": "Документ",
	"model.DocImage.created": "Дата создания",
	"model.DocImage.image": "Образ",
	"model.DepartmentsTreeFilter": "DepartmentsTreeFilter",
	"model.DepartmentsTreeFilter.name": "name",
	"model.Department": "Отдел",
	"model.Department.isArchive": "Архивный",
	"model.Department.chief": "Руководитель",
	"model.Department.subordinateDepartments": "Подчинённые отделы",
	"model.Department.projects": "Проекты",
	"model.Department.employees": "Сотрудники",
	"model.Department.name": "Наименование",
	"model.Department.disbanded": "Отдел расформирован",
	"model.Department.higherDepartment": "Вышестоящий отдел",
	"model.EmployeesReportFilter": "EmployeesReportFilter",
	"model.EmployeesReportFilter.department": "department",
	"model.Document": "Документ",
	"model.Document.location": "Размещение",
	"model.Document.images": "Образы",
	"model.Document.description": "Краткое описание",
	"model.Document.docNumber": "Номер",
	"model.Document.software": "ПО",
	"model.Document.title": "Название",
	"model.Document.supples": "Приложения",
	"model.Document.project": "Проект",
	"model.Document.regDate": "Дата создания",
	"model.Document.main": "Основной документ",
	"model.ResourceType": "ResourceType",
	"model.ResourceType.PersonalComputer": "ПК",
	"model.ResourceType.Phone": "Телефон",
	"model.ResourceType.Table": "Стол",
	"model.ResourceType.Notebook": "Ноутбук",
	"model.EmployeeAddress": "Адрес сотрудника",
	"model.EmployeeAddress.country": "Страна",
	"model.EmployeeAddress.address": "Адрес",
	"model.EmployeeAddress.city": "Город",
	"model.ByEmplFlt": "Фильтр Сотрудника",
	"model.ByEmplFlt.filterMode": "Режим сортировки",
	"model.ByEmplFlt.firstName": "Имя",
	"model.ByEmplFlt.lastName": "Фамилия",
	"model.ByEmplFlt.middleName": "Отчество",
	"model.Resource": "Ресурс",
	"model.Resource.cost": "Стоимость единицы",
	"model.Resource.description": "Описание",
	"model.Resource.responsible": "Ответственный",
	"model.Resource.passCost": "Стоимость амортизации",
	"model.Resource.usedBy": "Используются сотрудниками",
	"model.Resource.name": "Наименование",
	"model.Resource.isShared": "Разделяемый ресурс",
	"model.Resource.resType": "Тип ресурса",
	"model.Country": "Страна",
	"model.Country.name": "Название",
	"model.Country.archive": "Архивное значение",
	"model.Country.description": "Описание",
	"model.Country.code": "Код"
});