package ru.croc.ctp.jxfw.mojo;

import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;

import java.io.File;


public class EcoreProcessorTest {

    @Rule
    public final ExpectedException exception = ExpectedException.none();

    @Test
    public void testCheckFileAutogenerated(){

        //GENERATED_COMMENT_NEW_STYLE
        EcoreProcessor.checkFileAutogenerated(
                new File("src/test/resources/autogenerated/model-meta.js"));
        //GENERATED_COMMENT_OLD_STYLE
        EcoreProcessor.checkFileAutogenerated(
                new File("src/test/resources/autogenerated/resource.js"));
        // EMPTY FILE
        EcoreProcessor.checkFileAutogenerated(
                new File("src/test/resources/autogenerated/empty.txt"));
        // NOT GENERATED
        exception.expect(IllegalStateException.class);
        EcoreProcessor.checkFileAutogenerated(
                new File("src/test/resources/autogenerated/not-empty.txt"));

    }

}
