<?xml version="1.0" encoding="ASCII"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:xfw="http://ru.croc.ctp.jxfw/metamodel">
  <xfw:XFWPackage name="ru" nsURI="http://ru.croc.ctp.jxfw/XFWPackage/ru" nsPrefix="ru">
    <eSubpackages href="#/1"/>
  </xfw:XFWPackage>
  <xfw:XFWPackage name="croc" nsURI="http://ru.croc.ctp.jxfw/XFWPackage/ru/croc" nsPrefix="ru.croc">
    <eSubpackages href="#/2"/>
  </xfw:XFWPackage>
  <xfw:XFWPackage name="ctp" nsURI="http://ru.croc.ctp.jxfw/XFWPackage/ru/croc/ctp" nsPrefix="ru.croc.ctp">
    <eSubpackages href="#/3"/>
  </xfw:XFWPackage>
  <xfw:XFWPackage name="survey" nsURI="http://ru.croc.ctp.jxfw/XFWPackage/ru/croc/ctp/survey" nsPrefix="ru.croc.ctp.survey">
    <eSubpackages href="#/4"/>
    <eSubpackages href="#/5"/>
  </xfw:XFWPackage>
  <xfw:XFWPackage name="domain" nsURI="http://ru.croc.ctp.jxfw/XFWPackage/ru/croc/ctp/survey/domain" nsPrefix="ru.croc.ctp.survey.domain">
    <eClassifiers xsi:type="xfw:XFWClass" name="NullableBoolean" instanceClassName="ru.croc.ctp.survey.domain.NullableBoolean" keyTypeName="java.lang.String" persistenceType="FULL">
      <eAnnotations source="http://www.croc.ru/ctp/model/i18n"/>
      <eAnnotations source="http://www.croc.ru/ctp/model/objectProperties"/>
      <eStructuralFeatures xsi:type="xfw:XFWAttribute" name="isFlag">
        <eAnnotations source="http://www.croc.ru/ctp/model/i18n"/>
        <eAnnotations source="http://www.croc.ru/ctp/model/column"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      </eStructuralFeatures>
      <persistenceModule>JPA</persistenceModule>
    </eClassifiers>
  </xfw:XFWPackage>
</xmi:XMI>
